command:
  - uvicorn
  - main:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

env:
  - name: WAREHOUSE_ID
    value: "4e7b8de25b26878f"
  - name: CATALOG
    value: "retail_demo"
  - name: PIPELINE_SCHEMA
    value: "retail_data"
  - name: GOLD_SCHEMA
    value: "gold"
  - name: SILVER_SCHEMA
    value: "silver"
  - name: GENIE_SPACE_ID
    value: "01f16f2adbbb1923b74f76afda90fb91"
  - name: ORDER_EMAIL_TO
    value: "igotu9999@gmail.com"
  - name: ORDER_EMAIL_FROM
    value: "igotu9999@gmail.com"
  - name: ORDER_EMAIL_PASSWORD
    value: "PASTE_APP_PASSWORD_HERE"
  - name: SMTP_HOST
    value: "smtp.gmail.com"
  - name: SMTP_PORT
    value: "587"
